ssh_keys: "{{ lookup('env','SSH_PUBKEY') }}"
password: "{{ lookup('env','ROOT_PASSWORD') }}"
token: "{{ lookup('env','LINODE_ACCESS_TOKEN') }}"
www_repo: "christopheradams.github.io"
www:
  base_dir: "/srv/www"
git:
  base_dir: "/srv/git"
  clone:
    - "https://github.com/christopheradams/{{ www_repo }}.git"
    - "https://github.com/christopheradams/hello-wwworld.git"
  init:
    - "Org.git"
