---
email: webmaster@cxadams.com
ssh_keys: "{{ lookup('env','SSH_PUBKEY') }}"
ssh_fingerprint: "{{ lookup('env','SSH_FINGERPRINT') }}"
password: "{{ lookup('env','ROOT_PASSWORD') }}"
htpasswd: "{{ lookup('env','ROOT_HTPASSWD') }}"
linode_token: "{{ lookup('env','LINODE_ACCESS_TOKEN') }}"
do_token: "{{ lookup('env','DO_API_TOKEN') }}"
gitolite:
  admin_key: "{{ ssh_keys }}"
