---
- name: Install Elixir
  apt:
    deb: "https://packages.erlang-solutions.com/erlang/debian/pool/elixir_{{elixir_version}}-1~ubuntu~{{ubuntu_codename}}_all.deb"

- name: Install hex
  become: no
  command: mix local.hex --force

- name: Install rebar
  become: no
  command: mix local.rebar --force

- name: Uninstall previous Phoenix
  become: no
  ansible.builtin.expect:
    command: mix archive.uninstall phx_new
    responses:
      (?i)uninstall: "Y"
  tags: phoenix

- name: Install Phoenix
  become: no
  ansible.builtin.expect:
    command: mix archive.install hex phx_new {{phoenix_version}}
    responses:
      (?i)install: "Y"
  tags: phoenix

