- name: Download Erlang
  get_url:
    url: "https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_{{erlang_version}}-1~ubuntu~{{ubuntu_version}}_amd64.deb"
    dest: /tmp/

- name: Install Erlang
  apt:
    deb: "/tmp/esl-erlang_{{erlang_version}}-1~ubuntu~{{ubuntu_version}}_amd64.deb"
