# from https://github.com/asdf-vm/asdf-erlang
- name: Install system packages for building Erlang
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - autoconf
    - build-essential
    - fop
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libncurses5-dev
    - libpng-dev
    - libssh-dev
    - libwxgtk3.0-dev
    - m4
    - unixodbc-dev
    - xsltproc
  tags:
    - packages

- name: Download Erlang
  get_url:
    url: "https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_{{erlang_version}}-1~ubuntu~{{ubuntu_version}}_amd64.deb"
    dest: /tmp/

- name: Install Erlang
  apt:
    deb: "/tmp/esl-erlang_{{erlang_version}}-1~ubuntu~{{ubuntu_version}}_amd64.deb"
