---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
        'apt-transport-https',
        'ca-certificates',
        'curl',
        'software-properties-common',
        'python3-pip',
        'virtualenv',
        'python3-setuptools',
        'build-essential'
        ]

    - name: Enable universe repository
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ bionic universe"

    - name: Install user packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
        'arc-theme',
        'deja-dup',
        'duplicity',
        'git',
        'gnome-tweak-tool',
        'openssh-server',
        'python-gi',
        'samba',
        'silversearcher-ag',
        'thunderbird',
        'vim'
        ]

    - name: Add Emacs repository
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: Install Emacs
      apt: update_cache=yes name=emacs26 state=latest

    - name: Add Xmonad repository
      apt_repository:
        repo: ppa:gekkio/xmonad

    - name: Install XMonad
      apt: update_cache=yes name=gnome-session-xmonad state=latest
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
        'dmenu',
        'gnome-session-xmonad',
        'libx11-dev',
        'libxext-dev',
        'libxinerama-dev',
        'libxrandr-dev',
        'libxss-dev',
        'xmobar'
        ]

    - name: Add Google apt key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub

    - name: Add Google Chrome Repository
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install Google Chrome
      apt: update_cache=yes name=google-chrome-stable state=latest
