---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  roles:
    - common
    - ruby
    - node
    - elixir
    - haskell
    - desktop
    - docker
    - role: git-annex
      become: no
  vars:
    ubuntu_version: bionic
