---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  roles:
    - common
    - ruby
    - node
    - elixir
    - haskell
    - desktop
    - docker
    - role: ipfs
      become: no
    - role: git-annex
      become: no
      vars:
        git_annex_target: install-home
  vars:
    ubuntu_version: bionic
