---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  vars:
    apps_path: ~/bin

  tasks:
    - name: Ensure Apps directory exists
      file:
        path: "{{ apps_path }}"
        state: directory

    - name: Install Ganache
      become: no
      get_url:
        url: https://github.com/trufflesuite/ganache/releases/download/v2.1.2/ganache-2.1.2-linux-x86_64.AppImage
        dest: "{{ apps_path }}/ganache-2.1.2-linux-x86_64.AppImage"
        mode: u+x

    - name: Install Truffle
      npm:
        name: truffle
        global: yes
