---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  vars:
    elixir_version: 1.9.4-otp-22
    erlang_version: 22.2.3

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - apt-transport-https
        - autoconf
        - automake
        - build-essential
        - ca-certificates
        - curl
        - fop
        - inotify-tools
        - libffi-dev
        - libgl1-mesa-dev
        - libglu1-mesa-dev
        - libncurses5-dev
        - libpng-dev
        - libreadline-dev
        - libssl-dev
        - libtool
        - libwxgtk3.0-dev
        - libxslt-dev
        - libyaml-dev
        - m4
        - python3-pip
        - python3-setuptools
        - software-properties-common
        - unixodbc-dev
        - unzip
        - virtualenv
        - xsltproc

    - name: Enable universe repository
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ bionic universe"

    - name: Install user packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - arc-theme
        - deja-dup
        - duplicity
        - ffmpeg
        - git
        - gnome-tweak-tool
        - ibus-pinyin
        - jq
        - mplayer
        - openssh-server
        - python-gi
        - samba
        - silversearcher-ag
        - thunderbird
        - vim
        - vlc

    - name: Add Emacs repository
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: Install Emacs
      apt: update_cache=yes name=emacs26 state=latest

    - name: Add Xmonad repository
      apt_repository:
        repo: ppa:gekkio/xmonad

    - name: Install XMonad
      apt: update_cache=yes name=gnome-session-xmonad state=latest
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - dmenu
        - gnome-session-xmonad
        - libx11-dev
        - libxext-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxss-dev
        - xmobar

    - name: Install Gnome + Xmonad custom desktop
      copy:
        src: config/gnome-xmonad-custom.desktop
        dest: /usr/share/xsessions

    - name: Install Gnome + Xmonad custom session
      copy:
        src: config/gnome-xmonad-custom.session
        dest: /usr/share/gnome-session/sessions

    - name: Install asdf
      become: no
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf

    - name: Install asdf Erlang plugin
      become: no
      command: ~/.asdf/bin/asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
      args:
        creates:  ~/.asdf/plugins/erlang

    - name: Install Erlang
      become: no
      command: "~/.asdf/bin/asdf install erlang {{erlang_version}}"
      args:
        creates:  "~/.asdf/installs/erlang/{{erlang_version}}"

    - name: Set global Erlang
      become: no
      command: "~/.asdf/bin/asdf global erlang {{erlang_version}}"

    - name: Install asdf Elixir plugin
      become: no
      command: ~/.asdf/bin/asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
      args:
        creates:  ~/.asdf/plugins/elixir

    - name: Install Elixir
      become: no
      command: "~/.asdf/bin/asdf install elixir {{elixir_version}}"
      args:
        creates:  "~/.asdf/installs/elixir/{{elixir_version}}"

    - name: Set global Elixir
      become: no
      command: "~/.asdf/bin/asdf global elixir {{elixir_version}}"

    - name: asdf reshim
      become: no
      command: "~/.asdf/bin/asdf reshim"

    - name: Add NodeSource apt key
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: Add NodeSource Repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_12.x bionic main
        state: present

    - name: Install nodejs
      apt: update_cache=yes name=nodejs state=latest

    - name: Add Yarn apt key
      apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: Add Yarn Repository
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present

    - name: Install yarn
      apt: update_cache=yes name=yarn state=latest

    - name: Add Google apt key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub

    - name: Add Google Chrome Repository
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install Google Chrome
      apt: update_cache=yes name=google-chrome-stable state=latest
