---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  roles:
    - common
    - git
    - ruby
    - node
    - elixir
    - haskell
    - desktop
    - docker
  vars:
    ubuntu_version: bionic
