---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  roles:
    - common
    - development
    - desktop
  vars:
    ubuntu_version: bionic

  tasks:
    - name: Add Emacs repository
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: Install Emacs
      apt: update_cache=yes name=emacs26 state=latest

    - name: Add Xmonad repository
      apt_repository:
        repo: ppa:gekkio/xmonad

    - name: Install XMonad
      apt: update_cache=yes name=gnome-session-xmonad state=latest
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - dmenu
        - gnome-session-xmonad
        - libx11-dev
        - libxext-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxss-dev
        - xmobar

    - name: Install Gnome + Xmonad custom desktop
      copy:
        src: config/gnome-xmonad-custom.desktop
        dest: /usr/share/xsessions

    - name: Install Gnome + Xmonad custom session
      copy:
        src: config/gnome-xmonad-custom.session
        dest: /usr/share/gnome-session/sessions

    - name: Add NodeSource apt key
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: Add NodeSource Repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_12.x {{ubuntu_version}} main
        state: present

    - name: Install nodejs
      apt: update_cache=yes name=nodejs state=latest

    - name: Add Yarn apt key
      apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: Add Yarn Repository
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present

    - name: Install yarn
      apt: update_cache=yes name=yarn state=latest

    - name: Add Google apt key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub

    - name: Add Google Chrome Repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install Google Chrome
      apt: update_cache=yes name=google-chrome-stable state=latest

    - name: Add Brave Browser apt key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg

    - name: Add Brave Browser Repository
      apt_repository:
        repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
        filename: /etc/apt/sources.list.d/brave-browser-release.list

    - name: Install Brave Browser
      apt: update_cache=yes name=brave-browser state=latest
