---
- hosts: localhost

  tasks:
    - name: Load gnome-terminal profiles
      shell:
        cmd: dconf load /org/gnome/terminal/legacy/profiles:/
        stdin: "{{ lookup('file', 'config/gnome-terminal.conf') }}"
