---
- hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  roles:
    - common
    - ruby
    - node
    - elixir
    - golang
    - desktop
    - docker
    - role: ipfs
      become: no
  vars:
    ubuntu_release: 18.04
    ubuntu_codename: bionic
