---
- name : Install Webserver
  hosts: christopherad-web
  vars_files:
    - ./group_vars/christopherad_group.yml
  become: true
  roles:
    - common
    - hosts
    - node
    - ruby
    - git
    - webserver
    - websites
  vars:
    ubuntu_version: bionic
