---
- hosts: christopherad-web
  become: true
  vars:
    git_repo: https://github.com/christopheradams/christopheradams.io.git
    tmp_dir: /tmp/christopheradms.io
    www_dir: /srv/www/christopheradams.io

  tasks:
    - name: Clone website to tmp
      git:
        repo: "{{ git_repo }}"
        dest: "{{ tmp_dir }}"

    - name: Bundle install
      bundler:
        state: present
        chdir: "{{ tmp_dir }}"

    - name: npm install
      npm:
        path: "{{ tmp_dir }}"

    - name: npm build
      command: npm run build
      args:
        chdir: "{{ tmp_dir }}"

    - name: Jekyll build
      command: jekyll build -s {{ tmp_dir }} -d {{ www_dir }} --lsi

    - name: Remove tmp
      file:
        path: "{{ tmp_dir }}"
        state: absent
