---
- name : Install Webserver
  hosts: christopherad-web
  vars_files:
    - ./group_vars/christopherad_group.yml
  become: true
  roles:
    - common
    - hosts
    - node
    - ruby
    - gitolite
    - role: ipfs
      vars:
        ipfs_service: true
    - webserver
    - websites
  vars:
    ubuntu_release: 18.04
    ubuntu_codename: bionic
