---
- hosts: christopherad-web
  become: true
  vars:
    git_repo: "{{ git.base_dir }}/{{ www_repo }}.git"
    tmp_dir: "/tmp/{{ www_repo }}"
    www_dir: "{{ www.base_dir }}/{{ www_repo }}/public"
    hello_repo: "{{ git.base_dir }}/hello-wwworld.git"
    cxa_tmp_dir: "/tmp/cxa.la.git"
    cxa_dir: "{{ www.base_dir }}/cxa.la/public"
    stats_dir: "{{ www.base_dir }}/cxa.la/stats"

  tasks:
    - name: Clone website to tmp
      git:
        repo: "{{ git_repo }}"
        dest: "{{ tmp_dir }}"

    - name: Bundle install
      bundler:
        state: present
        chdir: "{{ tmp_dir }}"

    - name: Jekyll build
      command: jekyll build -s {{ tmp_dir }} -d {{ www_dir }}

    - name: Remove tmp
      file:
        path: "{{ tmp_dir }}"
        state: absent

    - name: Remove cxa.la
      file:
        path: "{{ cxa_dir }}"
        state: absent

    - name: Clone hello-wwworld
      git:
        repo: "{{ hello_repo }}"
        dest: "{{ cxa_dir }}"
        depth: 1
        separate_git_dir: "{{ cxa_tmp_dir }}"

    - name: Remove tmp
      file:
        path: "{{ cxa_tmp_dir }}"
        state: absent

    - name: Add stats dir
      file:
        path: "{{ stats_dir }}"
        state: directory
