---
- hosts: christopherad-web
  become: true

  tasks:
      - name: Update all packages
        apt:
            update_cache: yes
            upgrade: dist

      - name: Reboot
        shell: sleep 10 && /sbin/shutdown -r now 'Rebooting because of updated packages'
        args:
            removes: /var/run/reboot-required
        async: 300
        poll: 0
        ignore_errors: true

      - name: Wait for system to become reachable again
        wait_for_connection:
            delay: 60
            timeout: 300

      - name: Verify new update (optional)
        command: uname -mrs
        register: uname_result

      - name: Display new kernel version
        debug:
            var: uname_result.stdout_lines
