---
- hosts: christopherad-web
  become: true

  tasks:
    - name: Copy nginx configs
      copy:
        src: sites-available/
        dest: /etc/nginx/sites-available

    - name: Enable sites
      file:
        src: "/etc/nginx/sites-available/{{ item }}"
        dest: "/etc/nginx/sites-enabled/{{ item }}"
        state: link
      loop: ['cxa.la', 'stats.cxa.la', 'chris.raysend.com', 'christopheradams.io']

    - name: Set htpasswd
      htpasswd:
        path: /etc/nginx/passwdfile
        name: root
        password: "{{ htpasswd }}"
        owner: root
        group: root
        mode: 0644

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

    - name: Generate SSL certificates
      shell: certbot --nginx --cert-name {{ item }} -d {{ item }} --redirect --non-interactive --agree-tos --email {{ email}}
      loop: ['cxa.la', 'stats.cxa.la']

    - name: Generate SSL certificates with www
      shell: certbot --nginx --cert-name {{ item }} -d {{ item }} -d www.{{ item}} --redirect --non-interactive --agree-tos --email {{ email}}
      loop: ['christopheradams.io']

    - name: Crontab goaccess
      cron:
        name: "goaccess"
        minute: "*/5"
        job: /usr/bin/goaccess -f /var/log/nginx/access.log -o /srv/www/cxa.la/stats/index.html --time-format="\%H:\%M:\%S" --date-format="\%d/\%b/\%Y" --log-format="\%h \%^[\%d:\%t \%^] \"\%r\" \%s \%b \"\%R\" \"\%u\""
