---
- hosts: christopherad-web
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'build-essential']

    - name: Install Ruby packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['ruby', 'ruby-dev', 'libxslt-dev', 'libxml2-dev']

    - name: Update gem
      command: gem update --system

    - name: Install bundler
      gem:
        name: bundler
        state: latest
        user_install: no

    - name: Create server directories
      file:
        path: "{{ item }}"
        state: directory
      loop: ["{{ www.base_dir }}", "{{ git.base_dir }}"]

    - name: Init repositories
      command: git init --bare {{item}}
      loop: "{{ git.init }}"
      args:
        chdir: "{{ git.base_dir }}"

    - name: Clone repositories
      git:
        repo: "{{ item }}"
        dest: "{{ git.base_dir }}/{{ item | urlsplit('path') | basename }}"
        bare: yes
      loop: "{{ git.clone }}"
