---
- name : Install Webserver
  hosts: christopherad-web
  vars_files:
    - ./group_vars/christopherad_group.yml
  become: true
  roles:
    - common
    - node
    - ruby
    - git
    - webserver
  vars:
    ubuntu_version: bionic

  tasks:
    - name: Create server directories
      file:
        path: "{{ item }}"
        state: directory
      loop: ["{{ www.base_dir }}", "{{ git.base_dir }}"]

    - name: Clone repositories
      git:
        repo: "{{ item }}"
        dest: "{{ git.base_dir }}/{{ item | urlsplit('path') | basename }}"
        bare: yes
      loop: "{{ git.clone }}"
