---
- name: Ensure Apps directory exists
  file:
    path: "{{ apps_path }}"
    state: directory

- name: Install Ganache
  get_url:
    url: https://github.com/trufflesuite/ganache/releases/download/v{{ganache_version}}/ganache-{{ganache_version}}-linux-x86_64.AppImage
    dest: "{{ apps_path }}/ganache.AppImage"
    mode: u+x
  tags: ganache

- name: Install NPM packages
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - truffle

- name: Add Go Ethereum repository
  apt_repository:
    repo: ppa:ethereum/ethereum
  tags: geth

- name: Install Go Ethereum
  apt: update_cache=yes name=ethereum state=latest
  tags: geth

