---
- name: Ensure Apps directory exists
  file:
    path: "{{ apps_path }}"
    state: directory

- name: Install Ganache
  get_url:
    url: https://github.com/trufflesuite/ganache/releases/download/v2.4.0/ganache-2.4.0-linux-x86_64.AppImage
    dest: "{{ apps_path }}/ganache.AppImage"
    mode: u+x
  tags: ganache

- name: Install NPM packages
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - truffle
    - "@openzeppelin/cli"
