---
- name: Clone dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: ~/dotfiles

- name: Link dotfiles
  file:
    src: "~/dotfiles/{{ item.src }}"
    path: "~/{{ item.dest }}"
    state: link
  loop:
    - { src: dash/bash_aliases, dest: .bash_aliases }
    - { src: dash/bashrc, dest: .bashrc }
    - { src: dash/profile, dest: .profile }
    - { src: emacs/emacs.d, dest: .emacs.d }
    - { src: git/gitconfig, dest: .gitconfig }
    - { src: git/gitignore, dest: .gitignore }
    - { src: ruby/.gemrc, dest: .gemrc }
    - { src: ruby/irbrc, dest: .irbrc }
    - { src: vim/vim, dest: .vim }
    - { src: vim/vimrc-base16-grayscale-light, dest: .vimrc }
    - { src: X/xprofile, dest: .xprofile }
    - { src: xmobar/.xmobarrc, dest: .xmobarrc }
    - { src: xmonad, dest: .xmonad }

- name: Creat npm global directory
  file:
    path: ~/.npm-global
    state: directory

- name: Configure npm global installs
  command: npm config set prefix '~/.npm-global'

- name: Set xkb-options
  shell:
    cmd: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape', 'compose:ralt']"

- name: Load gnome-terminal profiles
  shell:
    cmd: dconf load /org/gnome/terminal/legacy/profiles:/
    stdin: "{{ lookup('file', '~/dotfiles/gnome-terminal/gnome-terminal.conf') }}"

# To dump the profiles:
#   dconf dump /org/gnome/terminal/legacy/profiles:/ > config/gnome-terminal.conf

# Samba
# sudo smbpasswd -a christopher
