---
- name: Install desktop packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - arc-theme
    - deja-dup
    - duplicity
    - gnome-tweak-tool
    - gparted
    - ibus-pinyin
    - kruler
    - mplayer
    - python-gi
    - samba
    - thunderbird
    - usb-creator-gtk
    - vlc

- name: Import config
  become: no
  import_tasks: config.yml

- name: Import Xmonad
  import_tasks: xmonad.yml

- name: Import pandoc
  import_tasks: pandoc.yml
  tags: pandoc

- name: Import Emacs
  import_tasks: emacs.yml

- name: Import Chrome
  import_tasks: chrome.yml

- name: Import Brave
  import_tasks: brave.yml

- name: Import Fonts
  become: no
  import_tasks: fonts.yml

- name: Import Blockchain
  become: no
  import_tasks: blockchain.yml

- name: Import Dropbox
  import_tasks: dropbox.yml
  tags: dropbox

- name: Import Dropbox
  import_tasks: darktable.yml
  tags: darktable

- name: Import rclone
  import_tasks: rclone.yml
  tags: rclone
