- name: Install desktop packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - arc-theme
    - deja-dup
    - duplicity
    - gnome-tweak-tool
    - ibus-pinyin
    - mplayer
    - python-gi
    - samba
    - thunderbird
    - vlc

- name: Import Xmonad
  import_tasks: xmonad.yml

- name: Import Emacs
  import_tasks: emacs.yml

- name: Import Chrome
  import_tasks: chrome.yml

- name: Import Brave
  import_tasks: brave.yml
