- name: Clone git-annex
  git:
    repo: git://git-annex.branchable.com/
    dest: "{{ git_annex_repo }}"
  tags: git-annex

- name: Setup git-annex
  command: stack setup
  args:
    chdir: "{{ git_annex_repo }}"
  tags: git-annex

- name: Build git-annex
  command: stack build
  args:
    chdir: "{{ git_annex_repo }}"
  tags: git-annex

- name: Install git-annex
  make:
    chdir: "{{ git_annex_repo }}"
    target: install-home
    params:
      BUILDER: stack
  tags: git-annex
