---
- name: Install gitolite package
  apt: name=gitolite3 state=latest

- name: Create git user
  user: name="{{ gitolite.user }}" home="{{ gitolite.homedir }}" shell=/bin/bash state=present

- name: Check if gitolite key exists
  stat: path="{{ gitolite.homedir }}/.gitolite/keydir/{{ gitolite.admin }}.pub"
  register: rc

- name: Set up Gitolite
  block:
    - name: Install Gitolite admin key
      copy: src="{{ gitolite.admin_key }}" dest="{{ gitolite.homedir }}/{{ gitolite.admin }}.pub" force=yes owner="{{ gitolite.user }}" group="{{ gitolite.user }}" mode=0640
    - name: Set up Gitolite admin
      command: gitolite setup -pk "{{ gitolite.homedir }}/{{ gitolite.admin }}.pub"
      become: yes
      become_user: "{{ gitolite.user }}"
    - name: Clean up the key
      file: path="{{ gitolite.homedir }}/{{ gitolite.admin }}.pub" state=absent
  when: not rc.stat.exists

- name: Enable git config keys for Gitolite
  lineinfile:
    path: "{{ gitolite.homedir }}/.gitolite.rc"
    regexp: "^(\\s*GIT_CONFIG_KEYS\\s+=>\\s+').*(',)$"
    line: "\\1.*\\2"
    backrefs: yes

- name: Add safe showrev config for Gitolite
  lineinfile:
    path: "{{ gitolite.homedir }}/.gitolite.rc"
    insertafter: 'GIT_CONFIG_KEYS'
    line: '    SAFE_CONFIG => {SHOWREV =>  "git show -C %s; echo"},'

- name: Enable local code directory for Gitolite
  lineinfile:
    path: "{{ gitolite.homedir }}/.gitolite.rc"
    regexp: "^(\\s*)(#\\s*)(LOCAL_CODE)(.*)(HOME)(.*)$"
    line: "\\1\\3\\4\\5\\6"
    backrefs: yes

- name: Enable repository specific hooks in Gitolite
  lineinfile:
    path: "{{ gitolite.homedir }}/.gitolite.rc"
    regexp: "^(\\s*)(#\\s*)('repo-specific-hooks',)"
    line: "\\1\\3"
    backrefs: yes
