---
- name: Install gitolite package
  apt: name=gitolite3 state=latest

- name: Create git user
  user: name="{{ gitolite.user }}" home="{{ gitolite.homedir }}" shell=/bin/bash state=present

- name: Check if gitolite key exists
  stat: path="{{ gitolite.homedir }}/.gitolite/keydir/{{ gitolite.admin }}.pub"
  register: rc

- name: Set up Gitolite
  block:
    - name: Install Gitolite admin key
      copy: src="{{ gitolite.admin_key }}" dest="{{ gitolite.homedir }}/{{ gitolite.admin }}.pub" force=yes owner="{{ gitolite.user }}" group="{{ gitolite.user }}" mode=0640
    - name: Set up Gitolite admin
      command: gitolite setup -pk "{{ gitolite.homedir }}/{{ gitolite.admin }}.pub"
      become: yes
      become_user: "{{ gitolite.user }}"
    - name: Clean up the key
      file: path="{{ gitolite.homedir }}/{{ gitolite.admin }}.pub" state=absent
  when: not rc.stat.exists

- name: Install gitolite config file
  copy:
    src: gitolite.rc
    dest: "{{ gitolite.homedir }}/.gitolite.rc"
    owner: "{{ gitolite.user }}"
    group: "{{ gitolite.user }}"
    mode: 0600
  tags: gl_admin

- name: Enable repository specific hooks in Gitolite
  lineinfile:
    path: "{{ gitolite.homedir }}/.gitolite.rc"
    regexp: "^(\\s*)(#\\s*)('repo-specific-hooks',)"
    line: "\\1\\3"
    backrefs: yes

- name: Create directory for site-local Gitolite code
  file:
    path: "{{ gitolite.homedir }}/local/hooks/repo-specific"
    state: directory
    owner: "{{ gitolite.user }}"
    group: "{{ gitolite.user }}"
    mode: 0700

- name: Install post-receive-email hook for Gitolite
  copy:
    src: /usr/share/doc/git/contrib/hooks/post-receive-email
    dest: "{{ gitolite.homedir }}/local/hooks/repo-specific/post-receive-email"
    owner: "{{ gitolite.user }}"
    group: "{{ gitolite.user }}"
    mode: 0755

- name: Set up Gitolite hooks
  become: yes
  become_user: git
  shell:
    cmd: gitolite setup --hooks-only

