---
- name: Add NodeSource apt key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add NodeSource Repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x {{ubuntu_codename}} main
    state: present

- name: Install nodejs
  apt: update_cache=yes name=nodejs state=latest
