---
- name: Install system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - apt-transport-https
    - build-essential
    - ca-certificates
    - curl
    - python3-dev
    - python3-gpg
    - python3-pexpect
    - python3-pip
    - python3-setuptools
    - software-properties-common
    - virtualenv

- name: Enable universe repository
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu/ {{ubuntu_version}} universe"

- name: Install user packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - ffmpeg
    - git
    - inotify-tools
    - jq
    - libimage-exiftool-perl
    - openssh-server
    - silversearcher-ag
    - vim
