---
- name: Install certbot
  community.general.snap:
    name: certbot
    classic: yes

- name: Install certbot alternatives
  alternatives:
    name: certbot
    link: /usr/bin/certbot
    path: /snap/bin/certbot

- name: Set certbot containment
  command: snap set certbot trust-plugin-with-root=ok

- name: Install Cloudflare DNS plugin for certbot
  snap:
    name: certbot-dns-cloudflare
  tags: cloudflare

- name: Add Cloudflare configuration
  lineinfile:
    path: $HOME/.secrets/certbot/cloudflare.ini
    line: "dns_cloudflare_api_token={{ cloudflare_token }}"
    create: yes
    mode: 0600
  tags: cloudflare
