---
- name: Install webserver packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - goaccess
    - nginx
    - python-passlib

- name: Import certbot
  import_tasks: certbot.yml
  tags: certbot

- name: Import sendmail
  import_tasks: sendmail.yml
  tags: sendmail

- name: Disable crontab mail
  cronvar:
    name: MAILTO
    value: "\"\""
  tags: cron

- name: Install fail2ban
  apt: name=fail2ban state=latest update_cache=yes
  tags: fail2ban

- name: Create journal conf directory
  file:
    path: /etc/systemd/journald.conf.d
    state: directory
  tags:
    - systemd
    - logs

- name: Configure journal size
  copy:
    src: size.conf
    dest: /etc/systemd/journald.conf.d/size.conf
  tags:
    - systemd
    - logs

