---
- name: Install webserver packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - certbot
    - goaccess
    - nginx
    - python-certbot-nginx
    - python-passlib

- name: Import sendmail
  import_tasks: sendmail.yml
  tags: sendmail
