---
- name: Install sendmail packages
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - sendmail
    - mailutils
    - sendmail-bin

- name: Define sendmail hub
  lineinfile:
    path: /etc/mail/sendmail.mc
    regexp: 'MAIL_HUB'
    insertafter: "MAILER(`smtp')dnl"
    line: "define(`MAIL_HUB', `{{ hostname }}.')dnl"
  tags: sendmailconfig

- name: Define sendmail local relay
  lineinfile:
    path: /etc/mail/sendmail.mc
    regexp: 'LOCAL_RELAY'
    insertafter: "MAIL_HUB"
    line: "define(`LOCAL_RELAY', `{{ hostname }}.')dnl"
  tags: sendmailconfig

- name: Configure sendmail
  expect:
    command: sendmailconfig
    responses:
      Configure sendmail with the existing \/etc\/mail\/sendmail\.conf\? \[Y\] : y
      Configure sendmail with the existing \/etc\/mail\/sendmail\.mc\? \[Y\] : y
      Reload the running sendmail now with the new configuration\? \[Y\] : y
    timeout: 120
  tags: sendmailconfig
