---
www:
  - html
  - christopheradams.io
  - stats.cxa.la
certs:
  - name: cxa.la
    domains: [cxa.la]
  - name: stats.cxa.la
    domains: [stats.cxa.la]
  - name: christopheradams.io
    domains:
      - christopheradams.io
      - www.christopheradams.io
